### PR TITLE
avoid get blocked in dumping when mysql connection is broken

### LINKED ISSUE #181: Dumpling hangs on Aurora backup
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Ran a dumpling backup against AWS RDS Aurora.

2. What did you expect to see?

The dumpling backup exits successfully.

3. What did you see instead?

From the dumpling side, there is 0 CPU utilization and no disk activity, yet dumpling does not terminate. 

From the Aurora side, it has finished sending data. From metrics, it looked like that no data had been sent from Aurora to dumpling for several hours.

```
mysql> show full processlist;
+------+----------------+---------------------+------------+---------+-------+----------------------+-----------------------+
| Id   | User           | Host                | db         | Command | Time  | State                | Info                  |
+------+----------------+---------------------+------------+---------+-------+----------------------+-----------------------+
|    5 | rdsadmin       | localhost           | NULL       | Sleep   |     1 | delayed send ok done | NULL                  |
|    6 | rdsadmin       | localhost           | NULL       | Sleep   |     2 | cleaned up           | NULL                  |
|   59 | rdsadmin       | localhost           | NULL       | Sleep   |   403 | delayed send ok done | NULL                  |
| 3318 | root           | 10.137.3.129:34252  | NULL       | Sleep   | 19416 | delayed send ok done | NULL                  |
| 3319 | root           | 10.137.3.129:34276  | NULL       | Sleep   |  2885 | cleaned up           | NULL                  |
| 3320 | root           | 10.137.3.129:34290  | NULL       | Sleep   | 16441 | cleaned up           | NULL                  |
| 3321 | root           | 10.137.3.129:34298  | NULL       | Sleep   |  2740 | cleaned up           | NULL                  |
| 3322 | root           | 10.137.3.129:34300  | NULL       | Sleep   | 17061 | cleaned up           | NULL                  |
| 3323 | root           | 10.137.3.129:34308  | NULL       | Sleep   | 16443 | cleaned up           | NULL                  |
| 3324 | root           | 10.137.3.129:34310  | NULL       | Sleep   | 16345 | cleaned up           | NULL                  |
| 3325 | root           | 10.137.3.129:34312  | NULL       | Sleep   | 16452 | cleaned up           | NULL                  |
| 3326 | root           | 10.137.3.129:34316  | NULL       | Sleep   |  2743 | cleaned up           | NULL                  |
| 3327 | root           | 10.137.3.129:34318  | NULL       | Sleep   | 16397 | cleaned up           | NULL                  |
| 3328 | root           | 10.137.3.129:34320  | NULL       | Sleep   | 16431 | cleaned up           | NULL                  |
| 3329 | root           | 10.137.3.129:34324  | NULL       | Sleep   | 16432 | cleaned up           | NULL                  |
| 3330 | root           | 10.137.3.129:34326  | NULL       | Sleep   | 16456 | cleaned up           | NULL                  |
| 3331 | root           | 10.137.3.129:34328  | NULL       | Sleep   | 16455 | cleaned up           | NULL                  |
| 3332 | root           | 10.137.3.129:34330  | NULL       | Sleep   | 16441 | cleaned up           | NULL                  |
| 3333 | root           | 10.137.3.129:34332  | NULL       | Sleep   |  2726 | cleaned up           | NULL                  |
| 3334 | root           | 10.137.3.129:34336  | NULL       | Sleep   | 17065 | cleaned up           | NULL                  |
| 3335 | root           | 10.137.3.129:34338  | NULL       | Sleep   |  2788 | cleaned up           | NULL                  |
| 3336 | root           | 10.137.3.129:34344  | NULL       | Sleep   | 16396 | cleaned up           | NULL                  |
| 3337 | root           | 10.137.3.129:34346  | NULL       | Sleep   | 16352 | cleaned up           | NULL                  |
| 3338 | root           | 10.137.3.129:34348  | NULL       | Sleep   |  2822 | cleaned up           | NULL                  |
| 3339 | root           | 10.137.3.129:34350  | NULL       | Sleep   |  2885 | cleaned up           | NULL                  |
| 3340 | root           | 10.137.3.129:34352  | NULL       | Sleep   |  2702 | cleaned up           | NULL                  |
| 3341 | root           | 10.137.3.129:34354  | NULL       | Sleep   | 16351 | cleaned up           | NULL                  |
| 3342 | root           | 10.137.3.129:34356  | NULL       | Sleep   |  2884 | cleaned up           | NULL                  |
| 3343 | root           | 10.137.3.129:34358  | NULL       | Sleep   | 16351 | cleaned up           | NULL                  |
| 3344 | root           | 10.137.3.129:34362  | NULL       | Sleep   | 16460 | cleaned up           | NULL                  |
| 3345 | root           | 10.137.3.129:34364  | NULL       | Sleep   | 16414 | cleaned up           | NULL                  |
| 3346 | root           | 10.137.3.129:34368  | NULL       | Sleep   | 16442 | cleaned up           | NULL                  |
| 3347 | root           | 10.137.3.129:34372  | NULL       | Sleep   |  4628 | cleaned up           | NULL                  |
| 3348 | root           | 10.137.3.129:34374  | NULL       | Sleep   |  2885 | cleaned up           | NULL                  |
| 3349 | root           | 10.137.3.129:34376  | NULL       | Sleep   |  2618 | cleaned up           | NULL                  |
| 3350 | root           | 10.137.3.129:34378  | NULL       | Sleep   |  2681 | cleaned up           | NULL                  |
| 3351 | root           | 10.137.3.129:34380  | NULL       | Sleep   |  2607 | cleaned up           | NULL                  |
| 3352 | root           | 10.137.3.129:34382  | NULL       | Sleep   | 16450 | cleaned up           | NULL                  |
| 3353 | root           | 10.137.3.129:34384  | NULL       | Sleep   | 16447 | cleaned up           | NULL                  |
| 3354 | root           | 10.137.3.129:34386  | NULL       | Sleep   | 17072 | cleaned up           | NULL                  |
| 3355 | root           | 10.137.3.129:34390  | NULL       | Sleep   |  2885 | cleaned up           | NULL                  |
| 3356 | root           | 10.137.3.129:34392  | NULL       | Sleep   | 16358 | cleaned up           | NULL                  |
| 3357 | root           | 10.137.3.129:34394  | NULL       | Sleep   | 16340 | cleaned up           | NULL                  |
| 3358 | root           | 10.137.3.129:34398  | NULL       | Sleep   |  2884 | cleaned up           | NULL                  |
| 3359 | root           | 10.137.3.129:34402  | NULL       | Sleep   |  2701 | cleaned up           | NULL                  |
| 3360 | root           | 10.137.3.129:34404  | NULL       | Sleep   | 16396 | cleaned up           | NULL                  |
| 3361 | root           | 10.137.3.129:34406  | NULL       | Sleep   |  2684 | cleaned up           | NULL                  |
| 3362 | root           | 10.137.3.129:34408  | NULL       | Sleep   | 16449 | cleaned up           | NULL                  |
| 3363 | root           | 10.137.3.129:34410  | NULL       | Sleep   |  2706 | cleaned up           | NULL                  |
| 3364 | root           | 10.137.3.129:34414  | NULL       | Sleep   |  2608 | cleaned up           | NULL                  |
| 3365 | root           | 10.137.3.129:34416  | NULL       | Sleep   |  2717 | cleaned up           | NULL                  |
| 3366 | root           | 10.137.3.129:34418  | NULL       | Sleep   | 16340 | cleaned up           | NULL                  |
| 3367 | root           | 10.137.3.129:34420  | NULL       | Sleep   | 16429 | cleaned up           | NULL                  |
| 3368 | root           | 10.137.3.129:34422  | NULL       | Sleep   | 16413 | cleaned up           | NULL                  |
| 3369 | root           | 10.137.3.129:34426  | NULL       | Sleep   |  2709 | cleaned up           | NULL                  |
| 3370 | root           | 10.137.3.129:34430  | NULL       | Sleep   |  2614 | cleaned up           | NULL                  |
| 3371 | root           | 10.137.3.129:34432  | NULL       | Sleep   | 16411 | cleaned up           | NULL                  |
| 3372 | root           | 10.137.3.129:34434  | NULL       | Sleep   | 16446 | cleaned up           | NULL                  |
| 3373 | root           | 10.137.3.129:34436  | NULL       | Sleep   | 16409 | cleaned up           | NULL                  |
| 3374 | root           | 10.137.3.129:34440  | NULL       | Sleep   | 16397 | cleaned up           | NULL                  |
| 3375 | root           | 10.137.3.129:34442  | NULL       | Sleep   | 16396 | cleaned up           | NULL                  |
| 3376 | root           | 10.137.3.129:34446  | NULL       | Sleep   | 16418 | cleaned up           | NULL                  |
| 3377 | root           | 10.137.3.129:34448  | NULL       | Sleep   | 16421 | cleaned up           | NULL                  |
| 3378 | root           | 10.137.3.129:34450  | NULL       | Sleep   | 16397 | cleaned up           | NULL                  |
| 3379 | root           | 10.137.3.129:34452  | NULL       | Sleep   |  2727 | cleaned up           | NULL                  |
| 3380 | root           | 10.137.3.129:34454  | NULL       | Sleep   | 16341 | cleaned up           | NULL                  |
| 3381 | root           | 10.137.3.129:34456  | NULL       | Sleep   |  2600 | cleaned up           | NULL                  |
| 3382 | root           | 10.137.3.129:34458  | NULL       | Sleep   |  2881 | cleaned up           | NULL                  |
| 3706 | rdsadmin       | localhost           | NULL       | Sleep   |     0 | cleaned up           | NULL                  |
| 3707 | newswriter_adm | 10.138.66.152:41488 | newswriter | Query   |     0 | starting             | show full processlist |
+------+----------------+---------------------+------------+---------+-------+----------------------+-----------------------+
```

4. Versions of the cluster

- Dumpling version (run `dumpling -V`):

```
Release version: v4.0.7-9-gb84f64f
Git commit hash: b84f64ff362cedcb795aa23fa1188ba7b7c9a7d7
Git branch:      master
Build timestamp: 2020-10-27 04:21:05Z
Go version:      go version go1.15.3 linux/amd64
```

- Source database version (execute `SELECT version();` in a MySQL client):

```
mysql> SELECT version();
+------------+
| version()  |
+------------+
| 5.7.12-log |
+------------+
1 row in set (0.00 sec)
```

5. Operation logs

Dumpling logs

```
Release version: v4.0.7-9-gb84f64f
Git commit hash: b84f64ff362cedcb795aa23fa1188ba7b7c9a7d7
Git branch: master
Build timestamp: 2020-10-27 04:21:05Z
Go version: go version go1.15.3 linux/amd64

[2020/10/30 15:43:05.700 +00:00] [INFO] [config.go:180] ["detect server type"] [type=MySQL]
[2020/10/30 15:43:05.700 +00:00] [INFO] [config.go:198] ["detect server version"] [version=5.7.12-log]
[2020/10/30 15:43:07.988 +00:00] [INFO] [ir_impl.go:208] ["get estimated rows count"] [estimateCount=2918441068]
[2020/10/30 20:17:36.882 +00:00] [INFO] [ir_impl.go:208] ["get estimated rows count"] [estimateCount=61042457]
[2020/10/30 20:18:37.658 +00:00] [INFO] [ir_impl.go:208] ["get estimated rows count"] [estimateCount=425612999]
```

Dumpling goroutines [goroutine.txt](https://github.com/pingcap/dumpling/files/5476601/goroutine.txt)
Dumpling goroutines (binary dump) [goroutine.bin.zip](https://github.com/pingcap/dumpling/files/5476608/goroutine.bin.zip)
   
6. Configuration of the cluster and the task

```
            - "--ca=/etc/rds-tls/rds-ca-2019-root.pem"
            - "--password=${PASSWORD}"
            - "--allow-cleartext-passwords"
            # FLUSH TABLES WITH READ LOCK is not allowed on Aurora
            - "--consistency=lock"
            - "-o=/backup/${JOB}"
            - "--database=${DATABASE}"
            - "--tables-list=${TABLES}"
            - "--rows=200000"
            - "--threads=64"
            - "--user=${DB_USER}"
            - "--host=${DB_HOST}"
            - "--port=3306"
            - "--filetype=csv"
```

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve? 
Fix #181 

`dumpling` may get blocked at fetching data from database server when the connection to the database server is closed due to some reason.

Here is the goroutine information:
```
goroutine 265 [IO wait]:
internal/poll.runtime_pollWait(0x8c159d8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00064c698, 0x72, 0xf00, 0xfc8, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00064c680, 0xc000820038, 0xfc8, 0xfc8, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x22b
net.(*netFD).Read(0xc00064c680, 0xc000820038, 0xfc8, 0xfc8, 0xc000022600, 0xc000897000, 0x64)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000a6e0a0, 0xc000820038, 0xfc8, 0xfc8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
github.com/go-sql-driver/mysql.(*buffer).fill(0xc000213e60, 0xc6, 0x0, 0x0)
	/Users/chauncy/code/goPath/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/buffer.go:90 +0x13c
github.com/go-sql-driver/mysql.(*buffer).readNext(0xc000213e60, 0xc6, 0xc000820fc4, 0x4, 0x3c, 0x0, 0x0)
	/Users/chauncy/code/goPath/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/buffer.go:119 +0x9c
github.com/go-sql-driver/mysql.(*mysqlConn).readPacket(0xc000213e60, 0x5668bc1, 0x711b3a7, 0x53, 0xc0, 0x71121e8)
	/Users/chauncy/code/goPath/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/packets.go:67 +0x120
github.com/go-sql-driver/mysql.(*textRows).readRow(0xc00083e780, 0xc001801dc0, 0x4, 0x4, 0x53, 0xc0)
	/Users/chauncy/code/goPath/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/packets.go:742 +0x55
github.com/go-sql-driver/mysql.(*textRows).Next(0xc00083e780, 0xc001801dc0, 0x4, 0x4, 0x1, 0x0)
	/Users/chauncy/code/goPath/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/rows.go:220 +0x86
database/sql.(*Rows).nextLocked(0xc00064c780, 0x4020000)
	/usr/local/go/src/database/sql/sql.go:2767 +0xd5
database/sql.(*Rows).Next.func1()
	/usr/local/go/src/database/sql/sql.go:2745 +0x3c
database/sql.withLock(0x5fecc20, 0xc00064c7b0, 0xc000ac70e8)
	/usr/local/go/src/database/sql/sql.go:3184 +0x6d
database/sql.(*Rows).Next(0xc00064c780, 0xc0009940c0)
	/usr/local/go/src/database/sql/sql.go:2744 +0x87
github.com/pingcap/dumpling/v4/export.(*rowIter).Next(0xc000945440)
	/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/v4/export/ir_impl.go:48 +0x2e
github.com/pingcap/dumpling/v4/export.WriteInsert(0x600a920, 0xc000904980, 0x602eb80, 0xc0008e0140, 0x5fe9b20, 0xc001801e00, 0x0, 0xf4240, 0x0, 0x0)
	/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/v4/export/writer_util.go:193 +0x7a2
github.com/pingcap/dumpling/v4/export.SQLWriter.WriteTableData(0xc0000fe000, 0x600a920, 0xc000904980, 0x602eb80, 0xc0008e0140, 0x0, 0x0)
	/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/v4/export/writer.go:86 +0x393
github.com/pingcap/dumpling/v4/export.dumpDatabases.func1.1(0x0, 0x0)
	/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/v4/export/dump.go:276 +0x851
github.com/pingcap/br/pkg/utils.WithRetry(0x600a920, 0xc000904980, 0xc000ac7f00, 0x5fe9b60, 0xc0000524e0, 0x0, 0x0)
	/Users/chauncy/code/goPath/pkg/mod/github.com/pingcap/br@v0.0.0-20201027124415-c2ed897feada/pkg/utils/retry.go:34 +0x7c
github.com/pingcap/dumpling/v4/export.dumpDatabases.func1(0xc0009b7f68, 0x0)
	/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/v4/export/dump.go:266 +0x16d
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000944b10, 0xc000905a40)
	/Users/chauncy/code/goPath/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/chauncy/code/goPath/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:54 +0x66
```

### What is changed and how it works?
1. Add `readTimeout` in dsn. The default value is `15m` and add a hidden configuration `read-timeout`.
2. Add `extraConn` in `connectionPool` to avoid recreating connections while writing metadata, etc.
3. Add context.CancelFunc in tableIR. When dumping progress fails, MySQL conn will employ `readUntilEOF` function to read the remained buffer which will waste a lot of time. For aws client, the retry logic is in their function. So we needn't wait for this and should quit directly.
4. When dumping progress fails, don't write metadata to improve efficiency.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
    Try to kill mysql socket connection while dumping. dumpling on master branch may get blocked. But dumpling built from this branch won't.

Related changes

 - Need to cherry-pick to the release branch

### Release note

- fix the problem that dumpling may get blocked when its connection to database server is closed

### CODE REVIEW

**Comment by lichunzhu** [comment]
Do we need an extra MySQL connection?

File: v4/export/config.go [hunk 1]
```diff
@@ -119,7 +119,10 @@ func (config *Config) String() string {
 
 // GetDSN generates DSN from Config
 func (conf *Config) GetDSN(db string) string {
-	dsn := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?charset=utf8mb4", conf.User, conf.Password, conf.Host, conf.Port, db)
+	// maxAllowedPacket=0 can be used to automatically fetch the max_allowed_packet variable from server on every connection.
+	// https://github.com/go-sql-driver/mysql#maxallowedpacket
+	dsn := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&readTimeout=30s&writeTimeout=30s&interpolateParams=true&maxAllowedPacket=0",
```
Comment (mightyguava) [inline v4/export/config.go:124]: is there any chance of mysql taking longer than 30 seconds to start sending data when the chunk size is large? Probably not right? Since you query by primary key?

Comment (lichunzhu) [reply v4/export/config.go:124]: Good point! How long do you think is appropriate? Or, are there any more suggestions?

Comment (lichunzhu) [reply v4/export/config.go:170]: How about keeping it 30s and make it configurable?

Comment (mightyguava) [reply v4/export/config.go:170]: I was genuinely curious if it can take over 30 seconds to start sending data when you are querying directly by primary key. Since it’s the time to first byte sent that seems highly unlikely so 30 seconds seems fine. I’m not sure though. Configurable sounds safest.

File: v4/export/config.go [hunk 2]
```diff
@@ -225,6 +228,8 @@ func (conf *Config) DefineFlags(flags *pflag.FlagSet) {
 	flags.Bool(flagCompleteInsert, false, "Use complete INSERT statements that include column names")
 	flags.StringToString(flagParams, nil, `Extra session variables used while dumping, accepted format: --params "character_set_client=latin1,character_set_connection=latin1"`)
 	flags.Bool(FlagHelp, false, "Print help message and quit")
+	flags.String(flagReadTimeout, "15m", "I/O read timeout for db connection. Should be a decimal number with a unit suffix, such as '30s', '1m30s'")
```
Comment (kennytm) [inline v4/export/config.go:231]:
```suggestion
	flags.Duration(flagReadTimeout, 15*time.Minute, "I/O read timeout for db connection.")
```

File: v4/export/config.go (hunk 1 above)
Comment (lichunzhu) [reply v4/export/config.go]: I have raised this variable to `15m` and make it configurable.

**Review by kennytm — APPROVED** [review]
LGTM
