### PR TITLE
Fix: dump all generated column table

### LINKED ISSUE #145: dump data failed with syntax error when the entire table is generated columns
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
```
dumpling -o . -P 4000 -u root -h host
```
2. What did you expect to see?
dump data successfully.
3. What did you see instead?
```
[2020/08/27 14:42:01.739 +08:00] [ERROR] [main.go:212] ["dump failed error stack info"] [error="SELECT  FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 12 near \"FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1\" "] [errorVerbose="err = SELECT  FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 12 near \"FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1\" \ngoroutine 1 [running]:\nruntime/debug.Stack(0x19aec00, 0xc000272f40, 0x19afec0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/pingcap/dumpling/v4/export.withStack(0x19aec00, 0xc000272f40, 0xc00018a000, 0xc0001a2c00)\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/export/error.go:59 +0x8f\ngithub.com/pingcap/dumpling/v4/export.GetColumnTypes(0xc000304180, 0x0, 0x0, 0xc00023ffe0, 0x18, 0x1dd1720, 0x1, 0x0, 0x0, 0x0, ...)\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/export/sql.go:263 +0x325\ngithub.com/pingcap/dumpling/v4/export.SelectAllFromTable(0xc00029e000, 0xc000304180, 0xc00023ffe0, 0x18, 0x1dd1720, 0x1, 0x1, 0xc00001a000, 0xcf, 0x0)\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/export/sql.go:141 +0x105\ngithub.com/pingcap/dumpling/v4/export.dumpTable(0x19c4cc0, 0xc0001a8cc0, 0xc00029e000, 0xc000304180, 0xc00023ffe0, 0x18, 0xc0003a1e00, 0x19c32c0, 0xc00029e000, 0xc0003f5350, ...)\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/export/dump.go:321 +0xc5\ngithub.com/pingcap/dumpling/v4/export.dumpDatabases(0x19c4cc0, 0xc0001a8cc0, 0xc00029e000, 0xc00031e0e0, 0x19c32c0, 0xc00029e000, 0x0, 0x0)\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/export/dump.go:232 +0x353\ngithub.com/pingcap/dumpling/v4/export.Dump(0x19c4d00, 0xc00018a000, 0xc00029e000, 0x0, 0x0)\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/export/dump.go:199 +0xc25\nmain.main()\n\t/Users/aytrack/gitproject/pingcap/dumpling/cmd/dumpling/main.go:210 +0x152a\n"] [stack="github.com/pingcap/dumpling/v4/log.Error\n\t/Users/aytrack/gitproject/pingcap/dumpling/v4/log/log.go:78\nmain.main\n\t/Users/aytrack/gitproject/pingcap/dumpling/cmd/dumpling/main.go:212\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204"]

dump failed: SELECT  FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 12 near "FROM `0247__TICASE_1512_WWSVHA`.`t` LIMIT 1"   
```
4. Versions of the cluster

    - Dumpling version (run `dumpling -V`):

        ```
        Release version: v4.0.3-12-g8e00b82
        Git commit hash: 8e00b826f68dda6734d69d7d5c96d082b0e88ee6
        Git branch:      master
        Build timestamp: 2020-08-27 06:25:31Z
        Go version:      go version go1.15 darwin/amd64
        ```

    - Source database version (execute `SELECT version();` in a MySQL client):

        ```
        +-------------------------------------------------------------------+
        | tidb_version()                                                    |
        +-------------------------------------------------------------------+
        | Release Version: v4.0.0-beta.2-1006-g6831e487a                    |
        | Edition: Community                                                |
        | Git Commit Hash: 6831e487a84c8bde625de8c73feec9e6ec02f426         |
        | Git Branch: master                                                |
        | UTC Build Time: 2020-08-23 13:37:28                               |
        | GoVersion: go1.13                                                 |
        | Race Enabled: false                                               |
        | TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
        | Check Table Before Drop: false                                    |
        +-------------------------------------------------------------------+
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `dumpling.log` for Dumpling if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - running command for Dumpling if possible

### PR DESCRIPTION
**Pull request by Abingcbc**
### What problem does this PR solve? 
Fix #145 

### What is changed and how it works?
Handling the case where selected field is empty

### Check List 

Tests 

 - Unit test

Side effects

Related changes

### CODE REVIEW

File: v4/export/dump_test.go [hunk 1]
```diff
@@ -195,3 +195,22 @@ func (s *testDumpSuite) TestDumpTableWhereClause(c *C) {
...
+func (s *testDumpSuite) TestDumpTableAllGeneratedColumns(c *C) {
+	mockConfig := DefaultConfig()
+	mockConfig.SortByPk = false
+	db, mock, err := sqlmock.New()
+	c.Assert(err, IsNil)
+	conn, err := db.Conn(context.Background())
+	c.Assert(err, IsNil)
+
+	showCreateTableResult := "CREATE TABLE a (a INT as (1))"
+	rows := mock.NewRows([]string{"Table", "Create Table"}).AddRow("a", showCreateTableResult)
```
Comment (lance6716) [inline v4/export/dump_test.go:208]: That error shows dumpling queried a SQL (which may triggered by other logic of dumpling), but `mock` was not configurated to receive that SQL. 

You may add `ExpectQuery` like these lines if you believe that's indeed an expected SQL.

Comment (Abingcbc) [reply v4/export/dump_test.go:208]: Thanks for your reply! I have solved the bug of unit test by adding more mock expectations.

**Review by kennytm — COMMENTED** [review]
thanks for the PR.

when a table contains only generated columns, it should produce an output with `COUNT(*)` empty rows, rather than skipping the table entirely, for instance producing

```sql
INSERT INTO `the_table` VALUES
(),
(),
(),
(),
();
```

could you add a test for that (e.g. reuse `tests/ignore_generate_column`)?

(you could use the CI if setting up the environment is too hard 😛)

File: v4/export/dump.go [hunk 2]
```diff
@@ -244,6 +245,11 @@ func dumpDatabases(ctx context.Context, conf *Config, connectPool *connectionsPo
 			if err != nil {
 				return err
 			}
+			if tableDataIRArray == nil {
+				log.Info(fmt.Sprintf("Skip to dump data of table %s.%s, "+
+					"because all of its columns are generated", dbName, table.Name))
```
[the remark this answers is not in the document]
Comment (Abingcbc) [reply v4/export/dump.go]: Thanks for your reply! I reorganized the logic and implemented through another method. I added an integration test like the one you mentioned, instead of a unit test because it is a little difficult to use data-dog to mock. If it is necessary, I will try to add one.

File: v4/export/sql.go [hunk 3]
```diff
@@ -204,7 +210,13 @@ func SelectAllFromTable(conf *Config, db *sql.Conn, database, table string) (Tab
...
 	}
 
-	query := buildSelectQuery(database, table, selectedField, buildWhereCondition(conf, ""), orderByClause)
+	var query string
+	// If all columns are generated
+	if selectedField == "" {
+		query = fmt.Sprintf("SELECT '' FROM `%s`.`%s`", database, table)
+	} else {
+		query = buildSelectQuery(database, table, selectedField, buildWhereCondition(conf, ""), orderByClause)
+	}
```
Comment (kennytm) [inline v4/export/sql.go:219]:
```suggestion
	queryField := selectedField
	// If all columns are generated
	if queryField == "" {
		queryField = "''"
	}
	query := buildSelectQuery(database, table, queryField, buildWhereCondition(conf, ""), orderByClause)
```

we still need to use `buildSelectQuery` so that database and table names containing `` ` `` can still be properly escaped.

File: v4/export/test_util.go [hunk 4]
```diff
@@ -115,8 +115,8 @@ func (m *mockTableIR) ColumnNames() []string {
 }
 
 func (m *mockTableIR) SelectedField() string {
-	if m.selectedField == "*" {
-		return ""
+	if m.selectedField == "*" || m.selectedField == ""{
+		return m.selectedField
 	}
 	return m.selectedField
```
Comment (kennytm) [inline v4/export/test_util.go:121]: umm so the entire function is just `return m.selectedField`? 😄

File: v4/export/writer_util.go [hunk 5]
```diff
@@ -175,13 +176,17 @@ func WriteInsert(pCtx context.Context, tblIR TableDataIR, w storage.Writer, file
...
-			row.WriteToBuffer(bf, escapeBackSlash)
+			if selectedField != "" {
+				if err = fileRowIter.Decode(row); err != nil {
+					log.Error("scanning from sql.Row failed", zap.Error(err))
+					return err
+				}
+				row.WriteToBuffer(bf, escapeBackSlash)
+			} else {
+				bf.WriteString("()")
+			}
```
Comment (kennytm) [inline v4/export/writer_util.go:189]: please update the `WriteInsertInCsv` function as well

**Review by kennytm — COMMENTED** [review]
rest LGTM

File: v4/export/writer_util.go (hunk 5 above)
Comment (Abingcbc) [reply v4/export/writer_util.go:189]: Thanks for your comments! I am a little bit unsure of what the `csv` file should look like? Is it a file with `COUNT(*)` empty lines?

Comment (kennytm) [reply v4/export/writer_util.go:189]: yes

**Review by kennytm — APPROVED** [review]
LGTM

**Review by lichunzhu — APPROVED** [review]
LGTM
