### PR TITLE
fix snapshot problem

### LINKED ISSUE #112: --snapshot argument doesn't work
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Run dumpling with `--snapshot` argument.

2. What did you expect to see?
Dump tables with given snapshot.

3. What did you see instead?
Dump tables with current snapshot.

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve? 
fix #112
1. Now dumpling use `db.Exec("set tidb_snapshot = ?")` to set `tidb_snapshot`, but this can only influence that connection. The connection pool's `tidb_snapshot` is not set.
2. Now dumpling get tables before we `set snapshot`, which means the fetched tables are not the tables we actually want. But for consistency "lock" it needs all tables to lock before the dump process.

### What is changed and how it works?
1. Add `SessionParams` in `conf`. After we adjust all the `SessionParams` dumpling will reset `sql.DB` with the new dsn. This can make sure all connections' session variable has been set.
2. Delete consistency snapshot. Current process order: 
    a. set snapshot ts into `session params`
    b. fetch all the tables.
    c. set consistency.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

Side effects

 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 
### Release note

- fix the problem that --snapshot argument can't work

### CODE REVIEW

File: v4/export/sql.go [hunk 1]
```diff
@@ -401,6 +397,49 @@ func CheckTiDBWithTiKV(db *sql.DB) (bool, error) {
...
+func isUnknownSystemVariableErr(err error) bool {
+	return strings.Contains(err.Error(), "Unknown system variable")
+}
+
+func resetDBWithSessionParams(db *sql.DB, dsn string, params map[string]string) (*sql.DB, error) {
+	support := make(map[string]string)
+	for k, v := range params {
+		v = wrapQuotes(v)
+		s := fmt.Sprintf("SET SESSION %s = %s", k, v)
+		_, err := db.Exec(s)
```
Comment (kennytm) [inline v4/export/sql.go:417]:
```suggestion
		s := fmt.Sprintf("SET SESSION %s = ?", k)
		_, err := db.Exec(s, v)
```

Comment (lichunzhu) [reply v4/export/sql.go:417]: I use this format at first, but at last this failed when I try to set `tidb_mem_quota_query`.
```log
[2020/06/30 18:39:05.433 +08:00] [ERROR] [main.go:191] ["dump failed error stack info"] [error="Error 1231: Variable 'tidb_mem_quota_query' can't be set to the value of '%!s(MISSING)'"] [errorVerbose="err = Error 1231: Variable 'tidb_mem_quota_query' can't be set to the value of '%!s(MISSING)'\ngoroutine 1 [running]:\nruntime/debug.Stack(0x19fc520, 0xc0001fc220, 0x19fd9e0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/pingcap/dumpling/v4/export.withStack(0x19fc520, 0xc0001fc220, 0xc000038000, 0xc000152570)\n\t/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/v4/export/error.go:59 +0x8d\ngithub.com/pingcap/dumpling/v4/export.resetDBWithSessionParams(0xc0001fe000, 0xc000152540, 0x2a, 0xc0001d2600, 0x2a, 0x0, 0x0)\n\t/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/v4/export/sql.go:389 +0x684\ngithub.com/pingcap/dumpling/v4/export.Dump(0x1a13400, 0xc000038090, 0xc00012cea0, 0x0, 0x0)\n\t/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/v4/export/dump.go:101 +0x327\nmain.main()\n\t/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/cmd/dumpling/main.go:189 +0x132f\n"] [stack="github.com/pingcap/log.Error\n\t/Users/chauncy/code/goPath/pkg/mod/github.com/pingcap/log@v0.0.0-20200511115504-543df19646ad/global.go:42\nmain.main\n\t/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/cmd/dumpling/main.go:191\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"]
```

Comment (lichunzhu) [reply v4/export/sql.go:417]: arguments:
```log
Running command: ['/Users/chauncy/code/goPath/src/github.com/pingcap/dumpling/bin/dumpling', '-T', 'TICASE_3204_WTHYZC.dumpsnap', '--dump-empty-database=false', '--snapshot', '2020-06-30 18:39:03', '-h', '127.0.0.1', '-P', '4000', '-u', 'root', '-p', '', '-o', '/var/folders/sr/_hc37vmj0db6ht4_w6rw34880000gn/T/tmptv4miiea']
```

Comment (kennytm) [reply v4/export/sql.go:417]: @lichunzhu why is it `%!s(MISSING)`

File: v4/export/config.go [hunk 2]
```diff
@@ -53,7 +53,7 @@ type Config struct {
 	FileType          string
 	EscapeBackslash   bool
 	DumpEmptyDatabase bool
-	TiDBMemQuotaQuery uint64
+	SessionParams     map[string]string
```
Comment (kennytm) [inline v4/export/config.go:56]: perhaps this should be

```suggestion
	SessionParams     map[string]interface{}
```

so that we could assign a number to it

File: v4/export/sql.go (hunk 1 above)
Comment (lichunzhu) [reply v4/export/sql.go:417]: Before db.Exec this variable's values is `"34359738368"`.  Maybe after translation it becomes `%!s(MISSING)`.

File: v4/export/config.go (hunk 2 above)
Comment (lichunzhu) [reply v4/export/config.go:56]: But we still have to transfer it to string for dsn 🤔

File: v4/export/sql.go [hunk 3]
```diff
@@ -427,7 +426,13 @@ func resetDBWithSessionParams(db *sql.DB, dsn string, params map[string]string)
 	}
 
 	for k, v := range support {
-		dsn += fmt.Sprintf("&%s=%s", k, url.QueryEscape(v))
+		var s string
+		if str, ok := v.(string); ok {
+			s = wrapQuotation(str)
```
Comment (kennytm) [inline v4/export/sql.go:431]: let's just wrap the quotation mark directly. the only case the `str` passes the `strings.HasPrefix` stuff is when user invokes dumpling as

```sh
./dumpling --snapshot "'stuff'"
```

which is so unnatural that there's no point supporting it.

```suggestion
			s = wrapStringWith(str, "'")
```

(the `wrapBackTicks` function probably has the same bug, let's check it in the future)

Comment (lichunzhu) [reply v4/export/sql.go:431]: ok

**Comment by lichunzhu** [comment]
@kennytm PTAL again
